name: Auto Assign Reviewer for Frontend PRs

on:
  pull_request:
    types:
      - labeled
      - opened

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
    - name: Assign Navojith as a reviewer
      uses: actions/github-script@v6
      with:
        script: |
          const reviewersToAdd = ['Navojith'];
          const labels = context.payload.pull_request.labels.map(label => label.name.toLowerCase());
          const currentReviewers = context.payload.pull_request.requested_reviewers.map(reviewer => reviewer.login);
          
          if (labels.includes('frontend')) {
            // Only add the reviewer if they aren't already in the list
            const reviewers = [...new Set([...currentReviewers, ...reviewersToAdd])];

            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: reviewers,
            });
          } else {
            console.log('No "frontend" label found; skipping reviewer assignment.');
          }
