name: Auto Assign Reviewer for Frontend PRs

on:
  pull_request:
    types:
      - labeled
      - opened

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Check for "frontend" label
        if: contains(github.event.pull_request.labels.*.name, 'frontend') || contains(github.event.pull_request.labels.*.name, 'Frontend')
        run: echo "Frontend label detected."

      - name: Assign Navojith as a reviewer
        uses: actions/github-script@v6
        with:
          script: |
            const reviewers = ['Navojith'];
            const { context, github } = require("@actions/github");
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: reviewers,
            });
